#!/bin/bash

echo "📱 在手机上运行 MD2 应用的步骤"
echo "================================"

echo ""
echo "🚀 方法1：使用Git传输到电脑构建（推荐）"
echo "=========================================="
echo "1. 在Termux中初始化Git仓库："
echo "   git init"
echo "   git add ."
echo "   git commit -m 'MD2 Termux App'"
echo ""
echo "2. 推送到GitHub/GitLab："
echo "   git remote add origin <your-repo-url>"
echo "   git push -u origin master"
echo ""
echo "3. 在电脑上克隆并构建："
echo "   git clone <your-repo-url>"
echo "   cd md2-termux-app"
echo "   # 使用Android Studio打开项目"
echo "   # 或者使用命令行："
echo "   ./gradlew build"
echo "   ./gradlew installDebug"
echo ""

echo "🚀 方法2：使用SCP直接传输"
echo "=========================="
echo "1. 从Termux传输到电脑："
echo "   scp -r md2-termux-app user@computer:~/projects/"
echo ""
echo "2. 在电脑上构建："
echo "   cd ~/projects/md2-termux-app"
echo "   # 使用Android Studio打开项目"
echo "   # 或者使用命令行："
echo "   ./gradlew build"
echo "   ./gradlew installDebug"
echo ""

echo "🚀 方法3：使用Termux API（如果可用）"
echo "===================================="
echo "1. 安装Termux API："
echo "   pkg install termux-api"
echo ""
echo "2. 使用Termux API分享文件："
echo "   termux-share md2-termux-app.apk"
echo ""

echo "📱 方法4：直接在手机上安装APK"
echo "=============================="
echo "1. 构建APK（在电脑上）："
echo "   ./gradlew assembleDebug"
echo ""
echo "2. 传输APK到手机："
echo "   adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "3. 或者手动传输："
echo "   - 将APK文件通过微信/QQ发送"
echo "   - 或者使用文件管理器传输"
echo "   - 在手机上点击安装"
echo ""

echo "🎯 推荐步骤："
echo "=============="
echo "1. 立即在Termux中运行Java程序测试"
echo "   ./build-ultimate.sh"
echo ""
echo "2. 初始化Git仓库"
echo "   git init && git add . && git commit -m 'Initial commit'"
echo ""
echo "3. 推送到GitHub"
echo "   git remote add origin <your-repo-url>"
echo "   git push -u origin master"
echo ""
echo "4. 在电脑上克隆并构建"
echo "   git clone <your-repo-url>"
echo "   # 使用Android Studio打开项目"
echo ""
echo "5. 构建并安装到手机"
echo "   ./gradlew installDebug"
echo ""

echo "💡 提示："
echo "========"
echo "- 如果您没有电脑，可以使用在线IDE（如GitHub Codespaces）"
echo "- 如果您有朋友有电脑，可以请他们帮您构建"
echo "- 您也可以使用Termux中的Java程序进行逻辑测试"
echo ""
echo "🎉 开始您的Android开发之旅吧！"
